spring:
  datasource:
    url: jdbc:h2:./h2db/sampledb;
    driverClassName: org.h2.Driver
    username: username
    password:
  jpa.hibernate.ddl-auto: update
  h2.console.enabled: true
  mvc.hiddenmethod.filter.enabled: true
  cloudinary:
    cloud_name: dgpm5eq2u
    api_key: 317481163955916
    api_secret: St2PXVyHEEH51ImRdbGbpClUCl0

